### ISSUE TITLE
multiple input bars

### ISSUE THREAD

**Issue by dylanjhunt** [CodeForKids/rubysadventure#24]
After the first put 'Hello World' you can select between two input bars at the bottom:

http://glui.me/?i=t1bhmcgbkb6h5vs/2014-06-28_at_7.42_PM.png/

**Comment by xldenis** [comment]
are those two seperate input bars or two lines?

**Comment by xldenis** [comment]
this issue has the same underlying cause as #23, @jules2689, @NickMilligan
